models:
  - name: "claude-3-sonnet"
    model_id: "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    max_retries: 3
    retry_delay: 1
    regions:
      - "us-east-1"
      - "us-west-2"
  
  - name: "amazon-nova"
    model_id: "us.amazon.nova-pro-v1:0"
    max_retries: 3
    retry_delay: 1
    regions:
      - "us-east-1"
      - "us-west-2"
